const MODULES = {
  CLIENTS: 'CLIENTS',
  ACTS: 'ACTS',
  USERS: 'USERS',
  WAREHOUSES: 'WAREHOUSES',
  CONSIGNMENT_NOTES: 'CONSIGNMENT_NOTES',
  WAYBILLS: 'WAYBILLS',
  REPORTS: 'REPORTS',
  MAILINGS: 'MAILINGS',
};

const ROLES = {
  GLOBAL_ADMIN: 'GLOBAL_ADMIN',
  ADMIN: 'ADMIN',
};

export { MODULES, ROLES };
