export const USERS_SET = 'USERS_SET';

export const USERS_DELETE = 'USERS_DELETE';
export const USERS_SET_USER = 'USERS_SET_USER';
export const USERS_SET_USER_COMPLETE = 'USERS_SET_USER';

export const AUTHORIZATION_COMPLETED = 'AUTHORIZATION_COMPLETED';
export const CURRENT_USER_LOGOUT = 'CURRENT_USER_LOGOUT';

export const EMPLOYEES_SET = 'EMPLOYEES_SET';
export const EMPLOYEES_DELETE = 'EMPLOYEES_DELETE';

export const ENQUEUE_TOAST = 'ENQUEUE_TOAST';
export const PROCESS_TOAST = 'PROCESS_TOAST';
