export const USERS_SET = 'USERS_SET';
export const USERS_DELETE = 'USERS_DELETE';
export const USERS_SET_USER = 'USERS_SET_USER';
export const USERS_SET_USER_COMPLETE = 'USERS_SET_USER';

export const AUTHORIZATION_COMPLETED = 'AUTHORIZATION_COMPLETED';
export const USER_PROFILE_SET = 'USER_PROFILE_SET';
export const CURRENT_USER_LOGOUT = 'CURRENT_USER_LOGOUT';

export const EMPLOYEES_SET = 'EMPLOYEES_SET';
export const EMPLOYEES_DELETE = 'EMPLOYEES_DELETE';

export const ENQUEUE_TOAST = 'ENQUEUE_TOAST';
export const PROCESS_TOAST = 'PROCESS_TOAST';

export const CLIENTS_SET = 'CLIENTS_SET';
export const CLIENTS_DELETE = 'CLIENTS_DELETE';

export const WAREHOUSES_SET = 'WAREHOUSES_SET';
export const WAREHOUSES_DELETE = 'WAREHOUSES_DELETE';

export const CONSIGNMENT_NOTES_SET = 'CONSIGNMENT_NOTES_SET';
export const CONSIGNMENT_NOTES_DELETE = 'CONSIGNMENT_NOTES_DELETE';

export const WAYBILLS_SET = 'WAYBILLS_SET';
export const WAYBILLS_DELETE = 'WAYBILLS_DELETE';
